services:
  ### CONFIGURATION MICROSERVICES
  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    networks:
      - kadan-net
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://config-server:${CONFIG_SERVER_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    container_name: eureka-server
    networks:
      - kadan-net
    ports:
      - "${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}"
    depends_on:
      config-server:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://eureka-server:${DISCOVERY_SERVER_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    networks:
      - kadan-net
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://api-gateway:${APP_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s

  ### BUSINESS MICROSERVICES

  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_FOLDER: notification-service
    container_name: notification-service
    networks:
      - kadan-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_FOLDER: user-service
    container_name: user-service
    networks:
      - kadan-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}

  verification_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_FOLDER: verification-service
    container_name: verification-service
    networks:
      - kadan-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}

  view_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_FOLDER: view-service
    container_name: view-service
    networks:
      - kadan-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}

  story_service:
    build:
      context: .
      dockerfile: ./story-service/Dockerfile
    container_name: story-service
    networks:
      - kadan-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}

networks:
  kadan-net:
    driver: bridge
    external: true
