services:
  ### CONFIGURATION MICROSERVICES
  config_server:
    build: ./config-server
    container_name: config_server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    env_file:
      - ./.env

  eureka_server:
    build: ./eureka-server
    container_name: eureka_server
    ports:
      - "${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}"
    depends_on:
      - config_server

  api_gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - config_server
      - eureka_server

  ### BUSINESS MICROSERVICES

  notification_service:
    build: .
    container_name: notification_service
    depends_on:
      - config_server
      - eureka_server

  user_service:
    build: .
    container_name: user_service
    depends_on:
      - config_server
      - eureka_server

  verification_service:
    build: .
    container_name: verification_service
    depends_on:
      - config_server
      - eureka_server

  view_service:
    build: .
    container_name: view_service
    depends_on:
      - config_server
      - eureka_server