server:
  port: ${PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_ISSUER}
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}

logging:
  pattern:
    dateformat: hh:mm
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
