spring:
  datasource:
    url: ${SERVICE_USER_DATABASE_URL}
    username: ${SERVICE_MYSQL_DATABASE_USER}
    password: ${SERVICE_MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

keycloak:
  server:
    url: ${KEYCLOAK_SERVER_URL}
  client:
    id: ${KEYCLOAK_CLIENT_ID}
    secret: ${KEYCLOAK_CLIENT_SECRET}
  realm: ${KEYCLOAK_REALM}
  auth:
    url:
      login: ${KEYCLOAK_AUTH_LOGIN_URL}
      logout: ${KEYCLOAK_AUTH_LOGOUT_URL}
      introspection: ${KEYCLOAK_AUTH_INTROSPECTION_URL}
  skip:
    defaultrole: ${KEYCLOAK_SKIP_ROLE}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME_SPRING}
  api_key: ${CLOUDINARY_API_KEY_SPRING}
  api_secret: ${CLOUDINARY_API_SECRET_SPRING}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v1/api-docs
