spring:
  datasource:
    url: ${SERVICE_VERIFICATION_DATABASE_URL}
    username: ${SERVICE_MYSQL_DATABASE_USER}
    password: ${SERVICE_MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v1/api-docs
